adding error msg

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,3 +11,7 @@ jobs:
 
       - name: Run a sample GitHub Action
         run: echo "This workflow ran successfully for this action"
+
+      - name: Simulating error
+        run: echo "Error taking place"; exit 1
+
